package com.geek.cinemax.ui.theme

import androidx.compose.ui.graphics.Color

// Geek Cinemax - Electric Purple & Cyber Neon Theme
val primaryLight = Color(0xFF6200EE)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8DDFF)
val onPrimaryContainerLight = Color(0xFF1D0061)
val secondaryLight = Color(0xFF03DAC6)
val onSecondaryLight = Color(0xFF000000)
val secondaryContainerLight = Color(0xFFC8FFF4)
val onSecondaryContainerLight = Color(0xFF00201A)
val tertiaryLight = Color(0xFFFF4081)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E2)
val onTertiaryContainerLight = Color(0xFF3E001D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F9FA)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFF8F9FA)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3033)
val inverseOnSurfaceLight = Color(0xFFF1F0F4)
val inversePrimaryLight = Color(0xFFD0BCFF)
val surfaceDimLight = Color(0xFFDAD9DE)
val surfaceBrightLight = Color(0xFFF8F9FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3F7)
val surfaceContainerLight = Color(0xFFECEEF1)
val surfaceContainerHighLight = Color(0xFFE7E8EC)
val surfaceContainerHighestLight = Color(0xFFE1E2E6)

val primaryDark = Color(0xFFBB86FC)
val onPrimaryDark = Color(0xFF3700B3)
val primaryContainerDark = Color(0xFF4F008C)
val onPrimaryContainerDark = Color(0xFFE8DDFF)
val secondaryDark = Color(0xFF03DAC6)
val onSecondaryDark = Color(0xFF003732)
val secondaryContainerDark = Color(0xFF005047)
val onSecondaryContainerDark = Color(0xFFC8FFF4)
val tertiaryDark = Color(0xFFFF80AB)
val onTertiaryDark = Color(0xFF56002A)
val tertiaryContainerDark = Color(0xFF7D003F)
val onTertiaryContainerDark = Color(0xFFFFD9E2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0B0E14) // Deep Cyber Black
val onBackgroundDark = Color(0xFFE2E2E6)
val surfaceDark = Color(0xFF0B0E14)
val onSurfaceDark = Color(0xFFE2E2E6)
val surfaceVariantDark = Color(0xFF44474E)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E6)
val inverseOnSurfaceDark = Color(0xFF2F3033)
val inversePrimaryDark = Color(0xFF6200EE)
val surfaceDimDark = Color(0xFF0B0E14)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF06090E)
val surfaceContainerLowDark = Color(0xFF1A1C1E)
val surfaceContainerDark = Color(0xFF1E2025)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

// Custom Geeky Genre Colors
val genreColor1 = Color(0xFFBB86FC) // Purple
val genreColor2 = Color(0xFF03DAC6) // Teal
val genreColor3 = Color(0xFFCF6679) // Pink/Red
val genreColor4 = Color(0xFFFFD600) // Cyber Yellow
val statusColor = Color(0xFF00E5FF) // Electric Cyan

val color_soft_white = Color(0xFFE0E0E0)
val color_silver = Color(0xFFBDBDBD)

val color_blue = Color(0xFF121212)
val color_cyan = Color(0xFF03DAC6)
